sudo: false
language: ruby
rvm:
  - 2.4.2
cache: bundler
before_install: gem install bundler -v 1.16.0
branches:
  only: [master]
script: $TASK
env:
  matrix:
    - TASK="bundle exec rspec"
    - TASK="bundle exec rubocop"

